/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.nareshak.demo.sample

import spock.lang.Specification

class AppTest extends Specification {
    def "Canary test"() {
        expect:
        true
    }
}
