/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nareshak.demo.sample;

import com.nareshak.demo.messageformatter.MessageFormatter;
import com.nareshak.demo.messageprovider.MessageProvider;

public class App {

    public static void main(String[] args) {
        MessageProvider messageProvider = new MessageProvider();
        MessageFormatter formatter = new MessageFormatter();
        String message = formatter.format(messageProvider.getMessage());
        System.out.println(message);
    }
}
